version: '3.8'

services:
  frontend:
    build: 
      context: ./fe
    ports:
      - "80:80"
    networks: 
      - api
  api:
    build:
      context: ./api      
    networks: 
      - api

networks: 
  api: